### ISSUE TITLE
Register the package (General registry)

### ISSUE THREAD

**Issue by ven-k** [JuliaComputing/NgSpice.jl#19]
@JuliaRegistrator register()

**Comment by ven-k** [comment]
@JuliaRegistrator register()

**Comment by KristofferC** [comment]
Did you install the JuliaRegistrator bot on the repo?

**Comment by ven-k** [comment]
Yes, the app is installed. (I can find the `installed` label on the installation page) However, the `Settings->Manage Access` doesn't have the entry.

**Comment by ven-k** [comment]
Trying to retrigger

@JuliaRegistrator register()

**Comment by KristofferC** [comment]
@JuliaRegistrator register()

**Comment by KristofferC** [comment]
Nope, it doesn't like me either..

**Comment by ChrisRackauckas** [comment]
It probably needs to be enabled on JC? @aviks

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by Keno** [comment]
@JuliaRegistrator register()

**Comment by aviks** [comment]
Sometimes Github drops webhooks, and that may be happening today. You can use the web registrator on juliahub in these situations.

**Comment by ven-k** [comment]
Trying once before moving to web registrator,

@JuliaRegistrator register()

**Comment by ven-k** [comment]
This [PR](https://github.com/JuliaRegistries/General/pull/33307) closes the issue
