### ISSUE TITLE
package capitalization: NgSpice?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaComputing/NgSpice.jl#3]
The capitalization of this package seems a bit odd. NgSpice, NGSpice, or NgSPICE all seem better. It's generally easier to fix these things early rather than later on when there are lots of entanglements.

**Comment by ven-k** [comment]
In the [manual](http://ngspice.sourceforge.net/docs/ngspice-html-manual/manual.xhtml#magicparlabel-21623) and [website](http://ngspice.sourceforge.net/download.html) they have preferred `Ngspice`. So I followed the same convention to be consistent.

**Comment by StefanKarpinski** [comment]
I've renamed the repo. I'll leave the rest to you.

**Comment by ven-k** [comment]
I've changed all `Ngspice` in the repo to `NgSpice`.
